import type { Metadata } from 'next'
import './globals.css'
import { Roboto } from 'next/font/google'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'

const roboto = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	subsets: ['latin'],
	display: 'swap'
})

export const metadata: Metadata = {
	title: 'Encashment',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={roboto.className}>
			<body>
				<Header />
				<main className="main">{children}</main>
				<Footer />
			</body>
		</html>
	)
}
